nix-community/vscode-nix-ide

src/linter.ts
`nix-instantiate --parse` does not just show you sytnax errors, it
also has a simple *static analysis* phase, which will check for
symbols that are not in scope.
For example, for the nix expression:
```
{ pkgs }:
openjdk
```
nix will highlight openjdk, which cannot work since it is not in
scope (user missed that it needs to be in `pkgs.openjdk`).
This is extremely helpful.
Note that `with pkgs;` will turn off this analysis inside of the
`with` expression subtree, because now nix cannot guarantee anything
about symbols (any symbol could dynamically come from `pkgs`, which is
unknown statically).
The fix itself is very easy, these messages don’t have a comma before
the at, so just changing the regex a bit gives us this feature.
=> feat(linter): Allow symbol errors to show (static analysys)

package.json
the provided default configuration uses 2 spaces for indentation,
which is what nixpkgs-fmt uses
=> provide default configuration for [nix] files

syntaxes/nix.YAML-tmLanguage
Reasoning:
- It's the theme's job to make variables or interpolation italic or not
- Some themes don't have a color for variables, resulting in whatever is inside the curly brackets being colored as string:
Themes should reset `meta.embedded` to the default text color.
=> fix: mark interpolation as meta.embedded instead of markup.italic

README.md, package.json, src/configuration.ts, src/formatter.ts
These changes allow the `formatterPath`:
-  to be an array; some formatters aren't a single command (e.g., `nix fmt` -- which itself insists on editing files in-place but can be made to only print to stdout, depending on the formatter configured).
- to take the filename as an argument; this allows formatters like treefmt (#241) which supports more than one language and thus requires the filename to determine (I'm guessing) the filetype (e.g., `cat default.nix | treefmt --stdout {file}`).
The latter is fairly dependent on the former which is why I've included it here instead of a separate PR.
=> formatterPath array and filename argument

src/client.ts
These changes fix the `command-exists` function usage such that the extension doesn't fail to activate if `enableLanguageServer` is `true` and `serverPath` is not in `$PATH`; which currently throws the following error:
With the changes in this PR, the error is properly handled:
Fixes #203.
=> fix: catch error if serverPath doesn't exist

README.md
A quick docs update to make it clearer that any (so far as I understand) language server which implements the LSP _should_ work with this extension. Addresses (or closes, even) #274.
=> feat: declare support for nil

README.md
The upstream (nixd) license is under LGPL though, I (author of nixd) explictly re-license configuration docs here in MIT.
Fixes: #337
=> docs: saying that nixd is tested and add an example

snippets.json
This may be pretty subjective, but as a long time user of this extension, the built-in snippets for `let` and `with` are pretty annoying in that they don't add a space to the end of the expansion and don't move the cursor there.
I believe there are two common use cases for the snippets, both of which are not very pleasant with the current version:
* writing a new expression:
```nix
let<tab>
```
... which gets expanded to
```nix
let |;
in
```
... to which I add my desired bindings. Now I want to continue after the `in`, but I can't without manually moving my cursor there.
* modifying an existing expression:
```nix
let<tab>{
...
}
```
... which gets expanded to
```nix
let |;
in{
...
}
```
... to which I add my desired bindings. Now I have to move after the `in` and add a space, so the code …
=> Improve snippet usability

shell.nix
To resolve
```
error: Package ‘nodejs-16.20.2’ is marked as insecure, refusing to evaluate.
Known issues:
- This NodeJS release has reached its end of life. See https://nodejs.org/en/about/releases/.
```
=> Take latest Node.js version in shell.nix by default

package.json, src/client.ts, src/extension.ts
Hi there. I've made a patch to resolve #362.
If something wrong with this PR, please feel free to point it out.
Thank you.
Add a command `> Nix IDE: Restart Language Server` to restart the language server (or simply start if not running).
https://github.com/nix-community/vscode-nix-ide/assets/41154684/55536c81-956b-4608-a771-6b789cc91ea4
=> feat: add restarting language server command

README.md, package.json, src/configuration.ts, src/global.d.ts, src/utils.ts, yarn.lock
https://github.com/nix-community/nixd/blob/main/nixd/docs/configuration.md#where-to-place-the-configuration
According to the above document, when defining the expr of options, only absolute paths can be used. This is very inconvenient for configuring across machines. Therefore, this PR introduces the [vscode-variables](https://www.npmjs.com/package/vscode-variables) package to support using `${workspaceFolder}` in configuration files to define paths.
before
```json
{
"nixd": {
"options": {
"nixpkgs": {
"expr": "import <nixpkgs> { }"
},
"nix-darwin": {
"expr": "(builtins.getFlake \"/absolute/path/to/flake\").darwinConfigurations.default.options"
}
}
}
}
```
after
```json
{
"nixd": {
"options": {
"nixpkgs": {
"expr": "import <nixpkgs> { }"
},
"nix-darwin": {
"expr": "(builtins.getFlake …
```
=> feat: support use vscode variables in settings

package.json, src/client.ts, src/configuration.ts
Workaround for #387 
This is based on https://github.com/dotnet/vscode-csharp/pull/7106 which was designed to solve a similar problem, as far as I can tell.
This could probably also be made more specific, e.g. with string matchers for error messages or things like that, but I'd probably advocate for language server implementations to fix their errors instead of making a complex configuration in the client.
To test, I configured
```jsonc
"nix.serverPath": "nixd",
"nix.hiddenLanguageServerErrors" : [
"textDocument/definition",
],
```
and it seems to work! I have also seen language server crash and things like that, but those are a separate matter and not fixable with this particular error handler.
=> feat: add setting to suppress error notifications

src/client.ts, src/configuration.ts, src/extension.ts
Ensure the client watcher and output channel are disposed during a restart before the new client is creates, and also show a helper warning when certain variables are changed that require a restart.
Also catch errors starting the client, so that our restart configuration change handler is still registered in case the user fixes their serverPath or something like that. Similarly, always register the restart command in case user wants to start using language server after
not using it before.
Closes #419
=> fix: reload language server client on restart

README.md, package.json
Fix #423
This PR changes `activationEvents` from `onStartupFinished` to `onLanguage:nix`. And starting from VSCode 1.74, `onLanguage` events will be generated automatically. So we can simply leave it blank.
Reference: https://code.visualstudio.com/api/references/activation-events#onLanguage
=> feat: delay activation

README.md
`nix fmt -- -` does not seem to work with `nixpkgs-fmt`. `nix fmt -- --` seems to work fine with `nixpkgs-fmt` and `nixfmt-rfc-style`.
closes #413
=> readme: updated formatterPath for nix fmt

README.md, docs/snippets/advanced-nil-settings.jsonc, docs/snippets/advanced-nixd-settings.jsonc, package.json, src/configuration.ts
As described in https://github.com/nix-community/vscode-nix-ide/issues/433#issuecomment-2596040064, since `nixpkgs-fmt`'s project is slowly sun-setting and `nixfmt` is taking over, we're changing the default for this extension.
Tests have been made on my end (on NixOS) : 
1. Installing [`nixfmt-rfc-style`](https://search.nixos.org/packages?channel=24.11&from=0&size=30&sort=relevance&type=packages&query=nixfmt-rfc-style)
2. Changing `nix.formatterPath` to `nixfmt`
3. Making sure it'll use it by disabling the `nix.enableLanguageServer = false`
4. Opened a .nix file made some fuzzy changes, saved and saw the content being formatted by `nixfmt`
5. I haven't seen any error message
=> fix: default to nixfmt formatter

src/client.ts
Issues a warning if the extension fails to find the configured LSP.
Related to #464, as it would've provided a nice clue as to where the issue was.
=> fix: issue warning on missing `nil`/`nixd`

shell.nix
=> fix: shell.nix with bun instead of yarn (fixes #473)

package.json
related issue: #287
the current descriptions of settings related to formatter are not clear enought. I lost a good couple of minutes to trying to debug why `nix.formatterPath` was not working, and I only found it out after looking at code (and found the #287 afterwards). This should really be documented in the setting description.
=> fix: clarify descriptions of formatter settings

language-configuration.json
1. Insert indent when pressing Enter after some symbols, e.g. after `=`.
2. Insert indent and outdent when pressing Enter in between some symbols. e.g. between `let` and `in`. Note, that vscode by default already does that for `{}`, `[]`, `()`. 
```nix
{
a = |
}
{
a = 
|
}
```
```nix
let |in {}
let
|
in {}
```
=> feat: auto-indent on pressed enter

language-configuration.json
Somehow missed this in the previous PR.
Before vs After this PR. (`|` is cursor)
Before:
```nix
a = ''|
lorem ipsum
''
a = ''
|
lorem ipsum
''
```
This PR:
```nix
a = ''|
lorem ipsum
''
a = ''
|
lorem ipsum
''
```
=> fix: add auto-indent for multi-line strings

README.md
Removed reference to nix3-fmt in nix.formatterPath example, since it's not actually a package but rather a manual page E.g., "nix3-fmt(1)"  used at https://man.archlinux.org/man/extra/nix/nix3-fmt.1.en.
Removed link and reference to repository "nixpkgs-fmt" that was archived by the owner on Jul 24, 2024 and is now read-only.  It has been replaced by the already mentioned nixfmt repository at https://github.com/NixOS/nixfmt.
=> docs (README.md): update readme.md

language-configuration.json
What this does, is when a text is selected and pressing <code>\`</code> it will surround with <code>\`\`</code> instead of replacing the selection with <code>`</code>.
=> feat: add backticks to surroundingPairs

package.json
Adds default configuration for file nesting for flake.lock.
This is similar to what other extensions for languages with lockfiles do, e.g. https://github.com/rust-lang/rust-analyzer/issues/13580.
It can be enabled/disabled globally via `explorer.fileNesting.enabled`.
Before:
After:
=> feat: set explorer.fileNesting for flake.lock
